#theme: Minimal
# Site
repository: nievesvvd/Curriculum
# favicon: images/favicon.ico (optional)

# Content configuration version
version: 2

# Personal info
name: Nieves Victoria Velásquez Díaz
title: Senior Software Developer
email: nvvelasquezdiaz@gmail.com
website: www.github.com/nievesvvd/Curriculum

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  nievesvvd
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: nieves-velasquez-0b0994139
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Javascript</mark> and <mark>Eating Pizza</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Working Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sngular People SA
        link: https://www.sngular.com
        # link_text: https://www.sngular.com
        sub_title: Senior Software Developer
        caption: October 2018 - Present
        quote: >
          Tech stack: Javascript, Node, Git, Jira, Dialogflow CX
        description: | # this will include new lines to allow paragraphs
            Work in small proyects, sometimes at the same time, to create functionalities to support various conversational assistants making them clever and allowing them to connect to other resources or APIs. This way we could create complex environments and let the end users do more with less.
            A real example would be: an user will give a list of people and a specific time to a virtual asistant and this will reserve a conference room and send an invitation to all participants just by the pettition of the client. 
      - layout: left
        title: Fundación I+D del Software Libre
        link: https://www.fidesol.org
        # link_text: https://www.fidesol.org
        sub_title: Software Developer
        caption: February 2018 - October 2018
        quote: >
          Tech stack: SQL Server, .Net
        description: | # this will include new lines to allow paragraphs
            Develop SQL stored procedures to facilitate and accelerate execution times so the database could be consumed easier by the clients via web.
      - layout: left
        title: Acoremp SL
        link: https://acoremp.com
        # link_text: https://acoremp.com
        sub_title: ERP Sage X3 Consultant
        caption: January 2017 - February 2018
        quote: >
          Tech stack: Sage X3, Eclipse
        description: | # this will include new lines to allow paragraphs
            Develop and create customized solutions for the differents clients, as well as giving them technical support over the software.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Granada University
        caption: 2011 - 2017
        sub_title: Computer Science Degree
        description: | # this will include new lines to allow paragraphs
          During my time at the university I learnt most of my key skills that I still use in my career such as teamwork and working to tight deadlines. I also worked during my last year learning to balance my time between work and study. 

          I helped some of my junior colleages with differents subjects and organized and lead various study groups.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
